### ISSUE TITLE
Why not both?

### ISSUE THREAD

**Issue by nikolasleblanc** [probot/semantic-pull-requests#42] opened 2019-01-25 16:46 UTC
This plugin seems to only do title, commit message, or (title or commit message), but not (title and commit message). Can it?

**Comment by CecileRobertMichon** [comment] 2019-02-27 00:59
+1 on this. 

Our use case is the following: GitHub doesn't let you choose a default squash commit message. Squashing a pull request with one commit would use that commit’s message, but squashing a pull request with more than one commit will use the pull request’s title for the commit message. We want to make sure that every single external contributor PR in our repo gets merged with a valid squash commit message so checking both would be beneficial for us. 

Ideally we would be able to check the squash commit message only (so PR title for multiple commits, commit for single commit).

**Comment by zeke** [comment] 2019-02-28 14:39
@CecileRobertMichon would only allowing "squash merging" on the repo work for your case?

<img width="790" alt="screen shot 2019-02-28 at 8 38 46 am" src="https://user-images.githubusercontent.com/2289/53574003-514f4b00-3b34-11e9-8c35-97d60b1085cd.png">

**Comment by CecileRobertMichon** [comment] 2019-02-28 17:38
@zeke not exactly. We already only allow squash merging. The issue is that I can't control how many commits are in a pull request and GitHub is inconsistent when squash merging commits. If there is a single commit, the commit message comes from the commit. If there are multiple commits, the commit message comes from the PR title. So checking only the commits or only the title is not sufficient since either may be used at squash time.

**Comment by zeke** [comment] 2019-02-28 17:45
Got it. There's an open issue about squashing single-commit PRs: https://github.com/probot/semantic-pull-requests/issues/17

I am pretty busy right now, but would happily accept and ship a PR that addresses this.

**Comment by clakech** [comment] 2019-04-24 11:39
We would like to have both to have consistency between PR titles and all commits 

Here is a first implementation / proposal https://github.com/probot/semantic-pull-requests/issues/42

**Comment by nikolasleblanc** [comment] 2019-04-24 12:07
https://github.com/probot/semantic-pull-requests/pull/46 @clakech I think you meant this PR of yours :)

**Comment by zeke** [comment] 2019-04-25 01:27
Resolved by https://github.com/probot/semantic-pull-requests/pull/46 -- this should be live within a few minutes.

**Closed by zeke** 2019-04-25 01:27 UTC
